newrelic/newrelic-diagnostics-cli

README.md
docs/Contributing.md

Hi! I'd love to contribute to a New Relic project and work on one of the issues listed. But before doing that, I'd like to suggest a change in the documentation to mention that this org and repo requires contributors to fork a repo rather than using the upstream version.
I got a 403 when attempting to push a branch against the upstream-remote repo:
```
remote: Permission to newrelic/newrelic-diagnostics-cli.git denied to MikeBLambert.
fatal: unable to access 'https://github.com/newrelic/newrelic-diagnostics-cli.git/': The requested URL returned error: 403
```
Mention that contributors are required to use a fork version of this repo in order to open a PR.
Change in the Readme.md file and Contributing.md

add comment about using a fork instead of the upstream repo

---

processOptions.go
registration/registration_test.go
tasks/base/config/appname.go
tasks/base/config/appname_test.go
tasks/base/config/collect.go
tasks/base/config/integrationTests.yml
tasks/base/config/licenseKey.go
tasks/base/config/licenseKey_test.go
tasks/base/config/proxyDetect.go
tasks/base/config/validateLicenseKey.go
tasks/base/config/validateLicenseKey_test.go
tasks/base/env/collectSysProps.go
tasks/base/env/env.go
tasks/base/log/collect.go
tasks/base/log/copy.go
tasks/base/log/logHelpers.go
tasks/taskHelpers.go

We have tasks that look into config file settings and environment variables to validate if a customer's configuration has been appropriately implemented, for example, Base/Config/AppName, Base/Config/ValidateLicenseKey, and Base/Config/ValidateHSM. The issue is that these tasks would possibly give a false positive result if the configuration has applied through JVM System Properties (in the case of the Java agent) because we do not collect and look at system properties yet, only env vars and settings in config files. 
1.Add a task for collecting system properties: Base/Env/CollectSysProps
2.Use the upstream payload from Base/Env/CollectSysProps in tasks that validate Java Agent configuration settings. Those tasks are:
Base/Config/Collect
Base/Config/AppName
Base/Config/LicenseKey …

Collect sys props and use them in relevant tasks

---

go.mod
tasks/infra/config/config.go
tasks/infra/config/config_test.go
tasks/infra/config/validateJMX.go
tasks/infra/config/validateJMX_test.go
tasks/infra/env/env.go
tasks/infra/env/nrjmxMbeans.go
tasks/infra/env/nrjmxMbeans_test.go
tasks/java/env/version.go
tasks/taskHelpers.go

Not an issue, we are adding new features that I'll describe in the next section. 
1)Adding a task Infra/Env/NrjmxBeans: Validate that the mbeans that the customer wants to query with the JMX integration are available for the integration to pull from.
2)Add two new fields to the struct JmxConfig found in the task Infra/Config/ValidateJMX: This task is mainly used by TSEs to troubleshoot that a JMX server cannot connect to our JMX integration, and not so much for a customer to understand WHY a connection is failing. This is because we only output the error found, but we do not judge what the error means.
With that same purpose of using this task only to provide data to TSEs to troubleshoot, I have added two new fields to this task struct that contains information about the Java version and …

Validate nrjmx mbeans

---

tasks/infra/config/config.go
tasks/infra/config/config_test.go
tasks/infra/config/validateJMX.go
tasks/infra/env/nrjmxMbeans.go

This PR addresses the issue listed and described here: https://github.com/newrelic/newrelic-diagnostics-cli/issues/1
The first part of this cmd (right before the pipe) fails in windows `echo "*:type=*,name=*" | nrjmx -hostname 127.0.0.1 -port 9999 --verbose true` with the error `"echo": executable file not found`
This makes sense because we are using the go built-in function exec.Command (https://golang.org/pkg/os/exec/#Command), which expects to take the name of an executable as the first parameter followed by a list of arguments that get passed to that executable `func Command(name string, arg ...string)`. 
So our cmd above runs like this: `exec.Command("echo", ":type=*,name=*")`
However, "echo" is not an executable but built-in command in Powershell.
1. Get Infra/Config/ValidateJMX to …

Issue 1/update infra config validate jmx forwindows

---

output/outputHelpers.go
tasks/infra/env/validateZookeeperPath_linux.go

Diagnostics CLI can fail to captured the nrdiag-output.json and nrdiag-output.zip when the Linux user is not running as the root user and has run `./nrdiag` instead of `sudo ./nrdiag`
the error will look like this:
```
Error writing output file open .//nrdiag-filelist.txt: permission denied
------Error creating output files.------
Please check to ensure you have rights to creating files in the local directory or specify a different output directory with -output-path
Error writing output file invalid argument
Error writing output file open .//nrdiag-filelist.txt: permission denied
------Error creating output files.------
Please check to ensure you have rights to creating files in the local directory or specify a different output directory with -output-path
Error writing output file invalid …
```

add comment on running Diagnostics CLI with `sudo -E`

---

tasks/infra/config/integrationsMatch.go
tasks/infra/config/integrationsMatch_test.go

The task Infra/Config/IntegrationsMatch incorrectly declares a failure for this validation if there is not a definition file for a specific integration installed.
A year ago, the infra agent updated their configuration to allow for no definition files:
https://docs.newrelic.com/docs/create-integrations/infrastructure-integrations-sdk/specifications/host-integrations-newer-configuration-format
1.Update this task so it will not provide a failure status for an OHI integration that has no definition file and that has infra agent version 1.8.0 or higher
2. Use the payload from Infra/Agent/Version to check on the infra version
These changes were tested in a linux box that had the infra agent installed, version 1.13. It had the kafka, JMX and Docker OHIs configured. The docker-config. yml did …

Update infra/config/integrations match

---

tasks/dotnetcore/env/versions.go
tasks/dotnetcore/requirements/netcore-version.go

1. The task DotnetCoreEnvVersions is not showing the errors when it is unable to find the .NET core SDK version. The error summary only says: "Error determining the version .NET Core installed" when we actually do have access to the error itself. So we just need to add it to the summary.
2. The payload of DotnetCoreEnvVersions (a slice of strings. Each string is supposed to be a version) is used as an upstream payload in the task DotNetCore/Requirements/DotNetCoreVersion. When iterating through that upstream payload, we were attempting to get major, minor digits for each item (`coreVersion`): `majorVer, minorVer, _, _ := tasks.GetVersionSplit(coreVersion)` . But what if the item we are iterating through is not a string that has well-defined digits we can parse through? Ex: `.NET Core …

bubble up error when we are unable to get dotnet core version

---

.github/workflows/rollback.yml
scripts/rollback.sh

The original PR to add a rollback workflow: https://github.com/newrelic/newrelic-diagnostics-cli/pull/52
exposed that this workflow needed some adjustments after we merged it, tested it, and found some errors. But, as mentioned in that previous PR, that was the whole purpose of merging that PR: To expose any possible production errors that were not shown when this rollback process was tested locally.
Some of the errors that we uncovered:
1) The workflow couldn't use the GH action library `thebritican/fetch-latest-release@v1` because I needed to specify a concrete real version such as `thebritican/fetch-latest-release@v2.0.0`
2) The command `aws s3 cp s3://${S3_BUCKET}/nrdiag/${PREVZIP} s3://${S3_BUCKET}/nrdiag/test/nrdiag_latest.zip --copy-props metadata-directive` was failing with the …

Add rollout workflow

---

usage/usage.go

Usage data for nrLicenseKey will send any License keys that passes our format check:
https://github.com/newrelic/newrelic-diagnostics-cli/blob/main/tasks/base/config/validateLicenseKey.go#L152
https://github.com/newrelic/newrelic-diagnostics-cli/blob/main/tasks/base/config/validateLicenseKey.go#L140
Regardless if they are valid or not for a new relic account: https://github.com/newrelic/newrelic-diagnostics-cli/blob/main/tasks/base/config/validateLicenseKey.go#L93
Meaning if a License key is an Ingest key, it will pass the format check and but it will fail the validation against the account, so this usage data will send to Haberdasher.
Originally I thought this should be fine, I do want to collect usage data on Ingest keys. However, I forgot that Haberdasher will also collect new relic …

only capture valid account License Keys and not Ingest keys

---

tasks/base/config/collect.go
tasks/node/config/agent.go
tasks/node/config/agent_test.go
tasks/node/env/dependencies.go
tasks/node/env/dependencies_test.go

As I study new tickets where nrdiag task fails to do its job, then I do my best to update the task so it will not fail in the future.
Recently I found a Node agent support ticket(https://newrelic.zendesk.com/agent/tickets/441655) where nrdiag failed for two tasks:
1) Base/Config/Collect: it should have thrown a warning or failure status because we did not collect a config file for the node agent. The reason we didn't notice this was a problem is because we did not take into account the env var users can configure to not use a config file: `NEW_RELIC_NO_CONFIG_FILE`.
2)Node/Config/Agent: We did not run many Node agent tasks they will only if Node/Config/Agent succeeds. Node/Config/Agent fails when it does not find a config file, but that is not a fair way to judge if a user has configured …

update some Node agent tasks

---

attach.go

All upload attachments were having their requests formed as if it were for s3. The diagnostics service endpoint likewise receiving invalid PUTs to its upload endpoint. 
This looks to be due to the check to determine if the upload URL supplied by the diagnostics service is an s3 URL by seeing if the URL contains the known s3 host for attachments supplied by an ENV var `S3_UPLOAD_URL`. Issue here is env var is likely to never be present in local environments in usage, or is a config var supplied at build time so the match always succeeds as an empty string.
Fix match to s3 hostname
There are two paths here
- Set `S3_UPLOAD_URL` as an application config var and inject that value in the build arguments as we do with other config values.
- Match to a string for the s3 domain s3.amazonaws.com
I …

fix(attach): replace s3 url env var check with s3 domain string

---

scripts/upload.sh

Release publishing seems to have broken from the github actions migration of the ubuntu-latest image from 18.04 => 20.04 which uses v2 of the aws CLI 
Background:
https://github.com/aws/aws-cli/issues/5262
https://github.com/actions/virtual-environments/issues/1816
This PR implements a suggested fix mentioned here:
https://github.com/aws/aws-cli/issues/5623#issuecomment-801240811
If this fails to work we can specify the image to ubuntu 18.04 in a follow up PR and allow more time to investigate

fix(upload): add env AWS_EC2_METADATA_DISABLED to upload script

---

.github/workflows/release.yml
scripts/upload.sh

Release publishing seems to have broken from the github actions migration of the ubuntu-latest image from 18.04 => 20.04 which uses v2 of the aws CLI
Background:
aws/aws-cli#5262
actions/virtual-environments#1816
Follow up to : https://github.com/newrelic/newrelic-diagnostics-cli/pull/81
Pin the release action to ubuntu 18.04 until we can purposefully migrate a solution to ubuntu 20.04

fix(release): set release github action to explicitly use ubuntu 18.04

---

tasks/infra/config/integrationsValidateJson.go

Small update to json validation of OHIS as the recommended way is to pass keys in uppercase.
This PR allow json validation to be compatible with the new and old format simply by lowercasing keys when comparing

update ohi case validation for ohis v4

---

releaseVersion.txt

For the next release of NRDiag we need to bump the version to 2.0.0
New version of NRDiag
Changed releaseVersion.txt to reflect change
Hopefully when we publish it works

Bumping the version to 2.0.0

---

.github/workflows/integration-tests.yml
.github/workflows/lint.yml

* golangci workflow action is failing due to being on an old version
* windows integration test is failing due to using the workflow `windows-latest` (which is 2022) while our tests us windows 2019.
* Have workflows run without error
* Update golangci to 1.45.2
* Pin the windows integration workflow to windows 2019

Resolve workflow issues

---

tasks/compatibilityVars/versions.go

https://newrelic.atlassian.net/browse/IHEDIAG-65 
Update the compatibility variables for .NET
I removed 5.0 from the .net framework variables as there is no .net framework 5.0 (.net 5 is .net core, [.net framework 4.8 is the last version of .net framework.](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/))
I added .net 6 to the .net core variables
This is covered by existing tests

Update .NET version compatibility variables

---

scripts/clean.sh
scripts/upload.sh

https://newrelic.atlassian.net/browse/IHEDIAG-74
Ensure only the last 2 versions are available for download at https://download.newrelic.com/nrdiag 
Updated upload.sh to include aws commands to find the oldest object and remove it.
Updated clean.sh to better clean up tests from upload.sh
I manually tested the script with a test bucket

chore: Update the upload script to clean up the oldest release

---

.github/workflows/compile.yml
scripts/build.sh

We don't support arm64.
Support arm64
Added build commands to build for arm64 for all 3 os's
Added `-s -w` to ldflags to remove debug info/symbols and reduce binary size (resulted in a 29.5% reduction in size!)
I have an arm based ec2 instance I tested with

feat: Build for arm64 and optimize binary size

---

tasks/infra/log/loglevelcheck.go
tasks/infra/log/loglevelcheck_test.go

The infra-agent now supports a new log configuration option rather than the `verbose` one. Verbose will be supported for the following two years, meanwhile some clients can start using the new configuration. See: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/#logging-variables
Check if verbose (also known as debug or trace level) is enabled using new the new log configuration.
Check if new configuration is set first.

Fix infra-agent verbose enabled

---

tasks/infra/log/collect.go
tasks/infra/log/collect_test.go
tasks/infra/log/log.go

The infra-agent now supports build-in log rotation, which might create additional log files other than the one specified in the configuration. See: https://github.com/newrelic/infrastructure-agent/blob/master/assets/examples/infrastructure/newrelic-infra-template.yml.example#L159
Add into nrdiag all infra-agent log files. 
Additionally to the log file specified in the log configuration, rotated filenames will be made with the file base name of the main one + date + gz extension (if compression is enabled)
Implementation relies on tasks.FindFiles function
NOTE: Marked as draft till infra-agent 1.28.0 is released.

include infra agent log gz files (#1)

---

tasks/base/config/collect.go
tasks/base/log/logHelpers.go
tasks/dotnetcore/agent/installed.go
tasks/dotnetcore/agent/installed_unix.go
tasks/dotnetcore/agent/installed_windows.go

https://github.com/newrelic/newrelic-diagnostics-cli/issues/114
Update the CLI to support the latest version of the .NET Core agent
Updated the various variables to include the new path for the .NET Core agent v10+
For the task, I added OS specific files to hold the variables, to avoid having to check `runtime` in the task.
smoke test on linux and windows.

fix(issue-114): Update .NET Core paths

---

tasks/base/log/logHelpers.go

Add `/logs` to the path for dotnetcore logs

fix: Update path for dotnet core logs

---

tasks/infra/agent/agent.go
tasks/infra/agent/connect.go
tasks/infra/agent/version.go
tasks/infra/agent/version_test.go

- Validate if the installed version of Infrastructure Agent is older than one or two years ago.
- Display an error or warning depending on the result.
- Use the Github API to fetch the release date for that version. The current infra agent metadata does not include the build date.

feat: validate release date of current infra agent version

---

.gitignore
dockerHelper_test.go
scripts/integrationTest.sh

Integration tests are failing
Updated the linux integration tests to use x64 instead of x86, and bumped the ubuntu image up to 22.04. 
`./scripts/integrationTests.sh`

fix: Updated linux integration test env

---

attach/attach.go
attach/attach_test.go
go.mod
go.sum
mocks/attach_mock.go

There is no permalink to the Diag CLI Output in New Relic's UI
To show where a customer can view the output of the Diag CLI runs
Return URL based on run conditions
go test ./...

Permalinks to run

---

scripts/build.sh
scripts/upload.sh

We need platform specific archives to support a 1 line installation method
To update the upload.sh script to create the needed archives
I updated the upload.sh script to create the needed archives. I also added logic to the code for deleting the old releases, it no longer uses the Last Modified date but rather just keeps the current version and previous version (as defined in the releaseVersion.txt file), and deletes anything else.
1. Make sure your local aws cli  is pointing at the [REDACTED]'s AWS account. There is a test bucket there. It currently has releases 2.3.3 and 2.3.4 there.
2. Update the releases in `releaseVersion.txt` to something like
```
majorMinor=2.3
buildNumber=5
currentReleaseVersion=2.3.5
prevReleaseVersion=2.3.4
```
3. Run
```
S3_BUCKET=[REDACTED] BUILD_NUMBER=5 …
```

feat: Release platform specific archives to download.newrelic.com

---

scripts/install/install.sh

IHEDIAG-311
Create an installation script for nrdiag on Linux to facilitate 1 line install and run
The script checks to make sure it's being run on Linux and either x64 or arm64. Linux x86 is no longer supported by nrdiag.
The script also checks for needed prereqs: cut, tar, gzip, sudo, curl
For curl, if it isn't installed, it will ask if the user wants to install it and try to install based on the distro.
By default it installs nrdiag to the pwd, but you can specify a specific directory with `DESTDIR`
The installation goes to a tmp dir then is moved to the final destination. The tmp dir is cleaned up unless there is an error, it's left intact if there's an error to assist with debugging.
The binary is just named `nrdiag` in the end, it removes the `_x64` or `_arm64`.
It only installs the …

feat: Install script for linux

---

scripts/install/install.ps1

IHEDIAG-311
Create an installation script for nrdiag on Windows to facilitate 1 line install and run
The script checks to make sure it's being run on Windows and a supported proc architecture (x64, x86, or arm64). 
It installs nrdiag to the pwd
The installation goes to a tmp dir then is moved to the final destination. 
If the zip file for the current version already exists in TEMP, it will skip re-downloading it.
If there are any existing `nrdiag.exe` or `nrdiag_${plat}.exe` files in the pwd, they will be deleted first.
The binary is just named nrdiag.exe in the end, it removes the _x64 or _arm64.
It only installs the latest version, version is not configurable.
Run the command below, reach out to me for the URL in slack
```
[Net.ServicePointManager]::SecurityProtocol = 'tls12, tls'; …
```

feat: Install script for Windows

---

scripts/rollback.sh
scripts/upload.sh

We need a rollback script
Also this error on release:
```
upload: ./nrdiag_2.4.1_Windows_x86.zip to s3://***/nrdiag/nrdiag_2.4.1_Windows_x86.zip
Completed 6 Bytes/6 Bytes (13 Bytes/s) with 1 file(s) remaining
upload: ./version.txt to s3://***/nrdiag/version.txt
copy failed: s3://***/nrdiag/nrdiag_2.4.1.zip to s3://***/nrdiag/nrdiag_latest.zip An error occurred (AccessDenied) when calling the GetObjectTagging operation: Access Denied
Error: Process completed with exit code 1.
```
1. Be able to rollback
2. Releases run without errors
The rollback script has been updated to remove all relevant files for the current version then update the `nrdiag_latest.zip` file to be the previous version. Also updates the version.txt file.
For the error on release:
Per …

feat: Rollback script

---

tasks/infra/env/clockSkew.go
tasks/infra/env/clockSkew_test.go

https://github.com/newrelic/newrelic-diagnostics-cli/issues/167
Fix the bug in Infra/Env/ClockSkew 
The type assertion error was occurring due to a type change in the payload for Infra/Agent/Connect from map[string]string to []string. (https://github.com/newrelic/newrelic-diagnostics-cli/pull/139)
Refactored task to work with collector urls being a []string, also refactored to allow for more testing
```
go test github.com/newrelic/newrelic-diagnostics-cli/tasks/infra/env
```

fix(infra): Infra/Env/ClockSkew

---

processTasks.go

https://newrelic.atlassian.net/jira/software/c/projects/IHEDIAG/boards/2062?modal=detail&selectedIssue=IHEDIAG-457
Only prompt the user to attach when they have provided a flag that indicates they want to attach
Wrap the prompt in a check for the attachment flags
Smoke test with no attachment flags, `-a`, and `-api-key`

fix: Diagnostics CLI Attach only when flags present

---

attach/attach.go

The "Uploading results to New Relic" line displays twice, it only needs to display once
Fix the cosmetic error in the output
Moved the log.Info to a different function
Here's what it looks like now:
```
Creating nrdiag-output.zip
Uploading results to New Relic
37.42 KiB / 37.42 KiB [==============================================] 100.00% 18.35 KiB/s 2s
13.35 KiB / 13.35 KiB [==============================================] 100.00% 22.25 KiB/s 0s
Successfully uploaded to account!! Find your latest run here:
```

feat: Fix output for uploading

---

output/output.go

https://github.com/newrelic/newrelic-diagnostics-cli/issues/184
Ensure filelist and json are in zip when using -output-path
Ensured to use filepath.Join to build paths
build it and run a task with -output-path and check the resulting zip to ensure it contains the filelist and json

fix: Issue 184

---

tasks/base/log/logHelpers.go
tasks/dotnet/config/agent_windows.go

* Dotnet/Config/Agent success formatting 
* `"Summary": "Found1.NET agent config files.",`
* Ruby logging env variables not included in logHelpers
* Fix Dotnet/Config/Agent formatting
* Add Ruby logging env variables
*  https://docs.newrelic.com/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration/#log_file_name
* https://docs.newrelic.com/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration/#log_file_path
* Updated the formatting to include spaces around the count of config files found
* `"Summary": "Found 1 .NET agent config files.",`
* Added the env variables for ruby logs
`go test ./...`
Smoke test on Windows
Smoke test on host with Ruby app

feat: Task updates

---

tasks/base/collector/connectEu.go
tasks/base/collector/connectEu_test.go
tasks/base/collector/connectUs.go
tasks/base/collector/connectUs_test.go
tasks/base/collector/connect_helpers.go

Base/Collector/Connect* tasks are failing
Update Base/Collector/Connect* tasks to properly detect collector connection
The new mongrel endpoint returns a 404 with `{}` for the body when the connection is successful. I updated the task to look for this.
`go test ./...`

fix: Base/Collector/Connect*

---

output/output.go
tasks/base/config/collect.go
tasks/fileCopyEnvelope_nix.go
tasks/fileCopyEnvelope_windows.go
tasks/infra/log/collect.go

IHEDIAG-649
Infra log collection can collect .exe files
Ensure no executable files are being collected
I updated the regex that is used in the Infra/Log/Collect task to be more specific. If the infra config has a log path that ends with `newrelic-infra.log`, the regex would be
* OLD:  `^newrelic-infra*`
* NEW: `^newrelic-infra.*(.gz|.zip|.log)`
I updated the FileCopyEnvelope struct with a function to check if a file is executable. For windows it just checks if the suffix is `.exe`. For Linux/Mac, it checks the file permissions as described in [this stack overflow](https://stackoverflow.com/questions/60128401/how-to-check-if-a-file-is-executable-in-go).
I updated the paths we search for config files to include the paths for Infra on Mac installed via brew. Taken from [this …

fix: No longer collect executable files

---

config/config.go
config/config_test.go
usage/usage.go

Unnecessary data in usage payload
Remove unnecessary data in usage payload
Removed lines that added data to payload
go test ./...

fix: Remove payload from usage data

---

output/output.go
tasks/base/config/config.go
tasks/base/config/config_test.go
tasks/base/config/validateHSM.go
tasks/base/config/validateHSM_test.go

HSM Refactor
Refactor High Security Mode task to only check env vars and configuration files.  No comparison no longer happens in the CLI and instead can be sent up to their account to compare against account settings in the UI.
- Took out license key dependency from HSM task.
- Only checks env vars and configuration files for high security mode
- (Bugfix) Check config file settings for HSM
- Output info if settings are found
go test ./..
smoke test

feat: High Security Mode Refactor

---

tasks/base/config/validateHSM.go
tasks/base/config/validateHSM_test.go

When a combination of environment variables and configuration files are found, but don’t contain any high security mode configurations, it should return None.  Through smoke testing, I found it returned an Info result, so we need to fix that.
Make sure a None result is returned.
Before returning an Info result, check if the summary and payload are both empty.
go test ./...
smoke test locally: 
- `go build`
- `cp ./newrelic-diagnostics-cli <path to service to run against> && cd <path to service to run against>`
- `NEW_RELIC_HIGH_SECURITY=false ./newrelic-diagnostics-cli -s <language of service>` OR `NEW_RELIC_HIGH_SECURITY=true ./newrelic-diagnostics-cli -s <language of service>` OR `./newrelic-diagnostics-cli -s <language of service>`
- `code nrdiag-output.json`
- …

fix: HSM None Result

---

.gitignore
tasks/infra/config/integrationsMatch.go
tasks/taskHelpers.go

NR-231490
Update Infra/Config/IntregrationsMatch to make integration_name optional if the configuration is v4.
Added logic to not check for integration_name if the file is v4.
I also noticed this failure:
```
Failure - Infra/Config/ValidateJMX
Unexpected results for jmx-config.yml: invalid configuration found: collection_files not set
```
The field collection_files is now in caps. Here is what the default yml looks like:
```
integrations:
- name: nri-jmx
env:
COLLECTION_FILES: "/etc/newrelic-infra/integrations.d/jvm-metrics.yml,/etc/newrelic-infra/integrations.d/tomcat-metrics.yml"
JMX_HOST: jmx-host.localnet
JMX_PASS: admin
JMX_PORT: "9999"
JMX_USER: admin
REMOTE_MONITORING: "true"
interval: 15s
labels:
env: staging
```
So I updated the `FindKeys()` config helper function to be case …

fix(NR-231490): Update Infra/Config/IntegrationsMatch: make integration_name optional

---

tasks/infra/agent/debug.go
tasks/infra/agent/version.go

The Infra/Agent/Version task does a check to ensure the agent version is not out of date by pulling the data from the github api. If that connection fails, the task returns an error. This causes Infra/Agent/Debug to not gather logs and to report that the agent is not installed when it actually is.
Have Infra/Agent/Debug run even if the agent version can't be checked against github.
Changed Infra/Agent/Version to return a warning when it can't validate the agent version isn't outdated.
Changed Infra/Agent/Debug to keep going even if Infra/Agent/Version had a warning.

fix(NR-268332): Changed infra/agent/version to warning if cant validate publish date

---

config/config.go
config/config_test.go
output/fixtures/test-output.json
output/fixtures/test-output_windows.json
output/fixtures/test-stream-output.json
output/fixtures/test-stream-output_windows.json
processOptions.go
tasks/k8s/flux/flux.go
tasks/k8s/resources/config.go
tasks/k8s/resources/daemonset.go
tasks/k8s/resources/deploy.go
tasks/k8s/resources/pods.go
tasks/k8s/resources/resources.go

On newest versions of AC 2 namespaces are used the main one and one for the agents.
This task allows adding a flag specifying an the extra namespace where the agent control agents reside.
The Resources will be scrapped from both namespaces,

feat: allow split-namespace gathering for AgentControl

---

.github/workflows/lint.yml
scripts/build.sh
scripts/publish.sh

When running the build script locally and testing, I do not receive any errors on any linux distros and the binary is statically linked
```
$ ldd nrdiag_x64
not a dynamic executable
```
However the binaries that are being built by our release pipeline result in the following errors on Rocky Linux 8:
```
./nrdiag: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./nrdiag)
./nrdiag: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./nrdiag)
```
which is caused by them being dynamically linked:
```
$ ldd nrdiag
./nrdiag: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./nrdiag)
./nrdiag: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./nrdiag)
linux-vdso.so.1 (0x00007ffd281ec000)
libc.so.6 => /lib64/libc.so.6 (0x00007f6869ace000) …
```

fix(glibc): Ensuring nrdiag uses pure Go
