tasks/base/env/initSystem.go
tasks/base/env/initSystem_test.go

It's addressing this GitHub issue: https://github.com/newrelic/newrelic-diagnostics-cli/issues/32
To summarize, our customers occasionally will get this error in the nrdiag output on their terminal:
```
Base/Env/InitSystem
Summary
Unable to parse init system from: /bin/busybox
```
A few customers and TSEs, have reached out to understand if this error is something they should concern about and fix on their end. Meaning that the error status, instead of filling the purpose of letting them know that nrdiag had an issue finding the initsystem, makes them think that they (the customer) caused the error and they are at fault.
1. Changing Status: `tasks.Error` to `tasks.None` if we could not determine the type of Linux system.
2. Adding a check for busybox (a popular type of linux flavor, that …

detect OpenRC init system for busybox

---

majorMinorVersion.txt

bump the major-minor version, from 1.11 to 1.12, for a new release of Diagnostics CLI

update majorminorversion.txt for new release

---

.github/workflows/release.yml

missing accessing some GH secrets needed for release workflow

add missing secrets to release workflow

---

tasks/compatibilityVars/versions.go

updated openJDK from 7.14 to 7.15. Updated HotSpot from 7.14 to 7.15

---

.github/workflows/rollback.yml

I forgot to add a specific version in the previous PR(https://github.com/newrelic/newrelic-diagnostics-cli/pull/52) for thebritican/fetch-latest-release

add latest version of thebritican/fetch-latest-release

---

scripts/rollback.sh

add quotes to args

---

.github/workflows/rollback.yml
scripts/rollback.sh

Add rollout workflow

---

.github/workflows/rollback.yml
scripts/rollback.sh

remove unknown aws args

---

.github/workflows/rollback.yml

checkout into code before doing git operation

---

usage/usage.go

Haberdasher is not receiving license keys values in their usage data. And whenever we do see values for the attribute `nrLicenseKey` [is not for connected to recent releases of nrdiag](https://staging-one.newrelic.com/launcher/dashboards.launcher?pane=eyJuZXJkbGV0SWQiOiJkYXNoYm9hcmRzLmRhc2hib2FyZCIsImVudGl0eUlkIjoiTVRBd01UTXdNVFI4VmtsYWZFUkJVMGhDVDBGU1JIeGtZVG8wTmpjIiwidXNlRGVmYXVsdFRpbWVSYW5nZSI6ZmFsc2UsImlzVGVtcGxhdGVFbXB0eSI6ZmFsc2UsInNlbGVjdGVkUGFnZSI6Ik1UQXdNVE13TVRSOFZrbGFmRVJCVTBoQ1QwRlNSSHd4TURNeE9EYyJ9&overlay=eyJpbml0aWFsQWN0aXZlSW50ZXJmYWNlIjoibnJxbEVkaXRvciIsImluaXRpYWxRdWVyaWVzIjpbeyJhY2NvdW50SWQiOjEwMDEzMDE0LCJucnFsIjoiU0VMRUNUIGZpbHRlcihjb3VudCgqKSwgd2hlcmUgbnJMaWNlbnNlS2V5VW5pcXVlQ291bnQgPiAwKSBhcyAncnVucyB3IGxpY2Vuc2Uga2V5JywgdW5pcXVlQ291bnQobnJMaWNlbnNlS2V5KSBhcyAndW5pcXV …

fix identifier name for licenseKeys

---

releaseVersion.txt

Bumping Version for new release.

version bump

---

README.md

Updated link to Docker install instructions and release notes link
Added link to download latest version
https://github.com/newrelic/newrelic-diagnostics-cli/issues/78
https://github.com/newrelic/newrelic-diagnostics-cli/issues/84
Add link in readme to make it clear where to find the latest version
Update link to Docker running instructions
n/a
n/a

Updating links in readme for reported issues

---

.github/workflows/compile.yml
.github/workflows/integration-tests.yml
.github/workflows/unit-tests.yml

integration tests not running for PRs to develop
all tests run
added develop branch to workflows

chore: Update workflows for develop branch

---

releaseVersion.txt

Release 2.2.0

---

README.md

Link to HTTPS to prevent CSP block of link to download

---

tasks/php/agent/version.go
tasks/php/agent/version_test.go

https://github.com/newrelic/newrelic-diagnostics-cli/issues/26
Update PHP version check to include versions in output. Include URL when multiple versions are detected
Added to task
Updated test
`go test ./tasks/php/agent -cover`

feat: PHP/Agent/Version - update warning if there are multiple versions

---

tasks/infra/config/integrationsCollect.go

https://github.com/newrelic/newrelic-diagnostics-cli/issues/31
Add warning message to integration collection 
I copied the pattern we were already using for the other secure files (adding a message to the result summary with a list of files excluded from the zip)
Run it on a vm with integration installed, check for message in output

feat: Add message to result summary regarding infra integration files excluded

---

.github/workflows/release.yml
releaseVersion.txt

Update release.yml and version.txt

---

tasks/infra/log/loglevelcheck_test.go

fix: Update test for ginkgo v2

---

.github/workflows/integration-tests.yml
.github/workflows/unit-tests.yml
scripts/integrationTest.sh
scripts/test.sh
tasks/base/config/integrationTests.yml

Integration tests
Fix them
Remove unnecessary lines
`./scripts/integrationTests.sh`

fix: Integration tests

---

go.mod
tasks/base/collector/collector.go
tasks/base/collector/connectTls.go
tasks/base/collector/connectTls_test.go
tasks/synthetics/minion/hordeConnect.go

https://newrelic.atlassian.net/browse/IHEDIAG-300
Add a new task that connects to https://connection-test.newrelic.com/ and parses the output to determine the TLS version used
Added a new task Base/Collector/ConnectTLS and tests
./scripts/test.sh
./scripts/integrationTest.sh

feat: New task Base/Collector/ConnectTLS to check tls version

---

releaseVersion.txt

Update version for release

---

tasks/fixtures/Android/Android-Sample/app/src/main/java/pknudsen/example/com/foobar/MainActivity_file.java

https://newrelic.atlassian.net/browse/IHEDIAG-335
Remove URLs that we don't own from tests
Removed the URLs
`go test ./...`

chore: Remove urls from testing

---

tasks/compatibilityVars/versions.go
tasks/python/env/dependencies.go
tasks/python/env/dependencies_test.go
tasks/python/env/version.go
tasks/python/env/version_test.go
tasks/python/requirements/pythonVersion.go
tasks/python/requirements/pythonVersion_test.go

Python was checking config files for agent version
To check output of pip freeze to see if new relic is installed and compare that against list of python versions that are installed in the user's system
Updated `Python/Env/Version`, `Python/Env/Dependencies`, `Python/Requirements/PythonVersion` and their respective unit tests.
Run the python suites and check that the `Python/Requirements/PythonVersion` output does not fail if you have python and the agent installed.  Also `go test ./...`

feat: Python Task Update

---

tasks/compatibilityVars/versions.go

Version compatibility for ruby was out of date
Update ruby version compatibility code to be current
Updated the map
```
go test github.com/newrelic/newrelic-diagnostics-cli/tasks/ruby/requirements
```

fix(ruby): Updated supported ruby versions

---

tasks/infra/env/validateZookeeperPath_linux.go
tasks/infra/env/validateZookeeperPath_linux_test.go

https://newrelic.atlassian.net/browse/IHUB-1790
No longer panic when checking for array with 0 length
Checked for length and unit tested
go test ./...

fix: Bugfix check for length

---

tasks/taskHelpers.go

Error message in base when running any task
Suppress error message
Changed info to debugs
Smoke test

fix: Debug instead of info

---

releaseVersion.txt

- The CLI now supports running scripts to gather additional output that isn't currently collected by a task. ([#182](https://github.com/newrelic/newrelic-diagnostics-cli/pull/182), [#185](https://github.com/newrelic/newrelic-diagnostics-cli/pull/185))
- Updated Hotspot versions supported by the Java APM agent. ([#183](https://github.com/newrelic/newrelic-diagnostics-cli/pull/183))
- Fixed an issue when using `-output-path` where the `nrdiag-filelist.txt` and `nrdiag-output.json` files were not included in the `nrdiag-output.zip`. ([#187](https://github.com/newrelic/newrelic-diagnostics-cli/pull/187))
- Fixed an issue that prevented some logs from being included in the zip. ([#188](https://github.com/newrelic/newrelic-diagnostics-cli/pull/188))

Release v3.1.0

---

usage/usage.go
usage/usage_test.go

Usage endpoint defaults to localhost
Use correct usage endpoint
Check directly for usage endpoint
Run

fix: Check for actual usage endpoint

---

releaseVersion.txt

Fixed an issue that prevented usage data from reporting ([190](https://github.com/newrelic/newrelic-diagnostics-cli/pull/190))

feat: Release 3.2.0

---

releaseVersion.txt

Release 3.2.1
- Added new task to check if the user executing the CLI has root permissions. ([#195](https://github.com/newrelic/newrelic-diagnostics-cli/pull/195))
- Updated `Infra/Log/Collect` to include relevant environment variables and default log locations. ([#195](https://github.com/newrelic/newrelic-diagnostics-cli/pull/195))
- Updated `Infra/Agent/Debug` to make log collection more reliable and to allow log collection to be interrupted gracefully. ([#195](https://github.com/newrelic/newrelic-diagnostics-cli/pull/195))
- Fixed an issue with `Base/Log/Copy` that resulted in a blank entry being added to the list of logs to copy. ([#195](https://github.com/newrelic/newrelic-diagnostics-cli/pull/195))
- Fixed the Success summary message for `Dotnet/Config/Agent`. …

Release 3.2.1

---

releaseVersion.txt

- Fixed an issue with Base/Collector/ConnectUS and Base/Collector/ConnectEU that caused the tasks to always return a Warning. ([#199](https://github.com/newrelic/newrelic-diagnostics-cli/pull/199))

feat: Release 3.2.2

---

releaseVersion.txt

- Fixed an issue that caused Base/Config/Validate to panic when parsing newrelic.js config files ([#202](https://github.com/newrelic/newrelic-diagnostics-cli/pull/202))

feat: Release 3.2.3

---

tasks/base/config/validate.go

https://github.com/newrelic/newrelic-diagnostics-cli/issues/205
Fix the panic
Added a check on the length of the array before trying to access [1]
go test ./...

fix: Fix validateJs panic

---

releaseVersion.txt

- Updated golang.org/x/net to version 0.17.0 to resolve CVE-2023-39325 ([#204](https://github.com/newrelic/newrelic-diagnostics-cli/pull/204))
- Fixed a panic in the Base/Config/Validate task when validating newrelic.js config files ([#206](https://github.com/newrelic/newrelic-diagnostics-cli/pull/206))
- Fixed an issue that could cause executable files to be included in the nrdiag-output.zip ([#207](https://github.com/newrelic/newrelic-diagnostics-cli/pull/207))

Release 3.2.4

---

scripts/test.sh
scripts/test_windows.ps1

fix: Update script

---

releaseVersion.txt

Release notes:
* Infra/Config/IntegrationMatch was updated to support infra-integrations-sdk v4 (#219)
* Adds better error handling to the FindFiles and FindProcessByName taskHelpers functions (#228)
* Update dependencies (#228)

Diagnostics CLI version 3.2.7

---

tasks/infra/agent/integrationTests_windows.yml

Fixes the flaky windows integration test

fix: Fix flaky integration test (windows)

---

releaseVersion.txt

Diagnostics CLI 3.3.0

---

releaseVersion.txt

* K8s/AgentControl/agent-control-install-job-logs - Collects logs generated by the agent-control installation

feat: Release 3.4.1
